name: Deploy on Dev
on:
    push:
        branches: [dev]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: ./scripts/dev-premaz.sh
            - name: Adding unit test to github actions
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v5
            - uses: php-actions/phpunit@v3
              with: 
                configuration: test/phpunit/phpunit.xml
                log_junit: test/phpunit/_junit/junit.xml
                memory_limit: 256M
